#!/bin/usr/env bash

export LESS="-FRSX"
export VISUAL="code"
export EDITOR=$VISUAL
export SSH_KEY_PATH="$HOME/.ssh/rsa_id"
export PATH=$HOME/.local/bin:$HOME/flutter/bin:$HOME/.dotnet/tools:$PATH
export PATH="$PATH:$HOME/go/bin"
export BAT_THEME="TwoDark"
export PROMPT_EOL_MARK=
export DOTNET_ROOT=/opt/dotnet
